services:
  mongo:
    image: mongo:7
    container_name: val-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    container_name: val-server
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      MONGO_URI: mongodb://mongo:27017/test
      PUBLIC_BASE_URL: http://localhost:4000
      VISITOR_SALT: change-me
      GEOLITE2_DB_PATH: /app/geo/GeoLite2-City.mmdb
    volumes:
      - ./server/geo:/app/geo:ro
      - ./server/uploads:/app/uploads
    depends_on:
      - mongo

volumes:
  mongo_data:
